import type { Knex } from 'knex';

/**
 * OAuth 2.1 authorization-server storage for the remote MCP endpoint.
 * Dialect-portable (SQLite dev/test, Postgres prod): `text` columns, JSON via
 * the knex `json` type, timestamps on every table. Access tokens are
 * self-contained JWTs and are NOT stored here — only clients (from dynamic
 * client registration), short-lived authorization codes, and refresh tokens.
 */
export async function up(knex: Knex): Promise<void> {
  // Dynamically-registered OAuth clients (RFC 7591). client_id/secret are
  // generated by the MCP SDK; we persist the registration.
  await knex.schema.createTable('oauth_clients', (t) => {
    t.text('client_id').primary();
    t.text('client_secret'); // null for public (PKCE) clients
    t.integer('client_id_issued_at');
    t.integer('client_secret_expires_at');
    t.json('redirect_uris').notNullable().defaultTo('[]');
    t.text('token_endpoint_auth_method');
    t.json('grant_types').notNullable().defaultTo('[]');
    t.json('response_types').notNullable().defaultTo('[]');
    t.text('scope');
    t.text('client_name');
    t.json('metadata').notNullable().defaultTo('{}'); // any extra registration fields
    t.timestamps(true, true);
  });

  // Short-lived authorization codes (authorization-code + PKCE flow).
  await knex.schema.createTable('oauth_auth_codes', (t) => {
    t.text('code').primary();
    t.text('client_id').notNullable().references('client_id').inTable('oauth_clients').onDelete('CASCADE');
    t.text('user_id').notNullable().references('id').inTable('users').onDelete('CASCADE');
    t.text('redirect_uri').notNullable();
    t.text('code_challenge').notNullable();
    t.text('code_challenge_method').notNullable().defaultTo('S256');
    t.text('scope').notNullable().defaultTo('');
    t.text('resource');
    t.integer('expires_at').notNullable(); // epoch seconds
    t.timestamps(true, true);
    t.index('client_id');
  });

  // Refresh tokens (hashed, never stored in plaintext).
  await knex.schema.createTable('oauth_refresh_tokens', (t) => {
    t.text('token_hash').primary();
    t.text('client_id').notNullable().references('client_id').inTable('oauth_clients').onDelete('CASCADE');
    t.text('user_id').notNullable().references('id').inTable('users').onDelete('CASCADE');
    t.text('scope').notNullable().defaultTo('');
    t.integer('expires_at'); // epoch seconds; null = no expiry
    t.timestamps(true, true);
    t.index('client_id');
    t.index('user_id');
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('oauth_refresh_tokens');
  await knex.schema.dropTableIfExists('oauth_auth_codes');
  await knex.schema.dropTableIfExists('oauth_clients');
}
